### ISSUE TITLE
macaca-desktop-sample 运行错误

### ISSUE THREAD

**Issue by sxyy** [macacajs/macaca-test-sample#1]
macaca run -d ./macaca-test/macaca-desktop-sample.test.js 
>> webdriver sdk launched
>> 

>> 

>>   macaca desktop sample

>> please run: `macaca install electron`

  TypeError: Cannot set property 'proxyMode' of undefined
      at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
      at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
`
提示要通过macaca install electron 但是实际上运行macaca install 又提示没有这个命令

macaca版本  1.1.0

**Comment by sxyy** [comment]
macaca doctor 运行结果 是少了什么吗


cvters-MacBook-Air:macaca-test-sample cvter$ macaca doctor

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v5.4.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/cvter/Documents/androidsdk/android-sdk-macosx`
  Platforms is set to `/Users/cvter/Documents/androidsdk/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/cvter/Documents/androidsdk/android-sdk-macosx/tools/android`

  Installed driver list:

  electron: 1.0.7

**Comment by xudafeng** [comment]
@sxyy 提示确实有问题，感谢反馈

**Comment by xudafeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1011681/17126336/ed823532-532e-11e6-849d-71524489e242.png)

**Comment by xudafeng** [comment]
请升级

```
$ npm i macaca-cli -g
```

然后全局安装 macaca-electron就好

**Comment by xudafeng** [comment]
如果是sample，执行 `make test-pc` 试试

**Comment by sxyy** [comment]
解决
